### ISSUE TITLE
Module path inconsistent with README and VCS URL 

### ISSUE THREAD

**Issue by ExalDraen** [choria-io/go-external-agent#9]
The current module path in go.mod is `github.com/choria-io/go-external-agent`. 

However, based on the URL of the repo I would expect this to be `github.com/choria-io/go-external` (no -agent at the end).

The example given in the README actually uses the expected module path of `github.com/choria-io/go-external` and so _it does not compile_. 

```
go: finding github.com/choria-io/go-external/agent latest
go: finding github.com/choria-io/go-external latest
go: github.com/choria-io/go-external@v0.0.0-20190925162635-e84cba4b1f89: parsing go.mod: unexpected module path "github.com/choria-io/go-external-agent"
go: error loading module requirements
```

I suggest the module path be changed to be of the expected form. I will submit a PR to this effect.

**Comment by ripienaar** [comment]
thank you @ExalDraen

**Comment by ripienaar** [comment]
@ExalDraen I'd be interested in your feedback on this libary, hadn't made a release yet as I hoped to expose it via https://github.com/containous/yaegi to let one just drop .go files into the lib dirs - but on reflection that would be a giant pain to make work.

So I'll look to make a release soon of this as is for now, but be interested in your feedback if you're playing with it

**Comment by ExalDraen** [comment]
I'd be happy to provide what feedback I can. What's the best medium? I can create issues but I'm not sure that's the best for conversation!

Right now, I've come across the following things that would be great to smooth out:

* A more fleshed out recipe for how to go about laying out a repo to make it easy to both develop the go code _and_ package the Puppet code. In a perfect world, this would include some CI config for circleCI/travis/github actions that can do packaging. Perhaps best as an example agent repo that people can just clone.

* Some more examples of actions that take no parameters, actions that read config, etc. Basically, examples that explore the API surface a bit more

* Less sure about this but: a way to package a go-based external agent such that the Go binary can optionally be downloaded from somewhere, instead of being included in the Puppet module. Given that Go binaries always include the Go runtime they are > 2MB so they massively increase the size of a puppet module in relative terms. 

FYI my in-progress agent based on this library: https://github.com/ExalDraen/choria-plugin-user-agent

**Comment by ripienaar** [comment]
We can chat on slack too - I am just traveling at the moment back next week.

I tried to reproduce the no inputs bug - its definitely a bug - https://github.com/choria-io/mcorpc-agent-provider/pull/125 couldnt, if you could file a issue there in that repo and include the JSON ddl I can take a peek

Yeah the size is a concern, i want you to just put a .go file in the directory and it will be compiled on demand but still on that - hence this repo not had any release just yet
